### PR TITLE
Fixes issues when a config file is not available

### LINKED ISSUE #5: Make stubborn.js config file non-mandatory
When I set config using `stubborn.start({myconfobj})` I expect that `stubborn.js` is no longer going to be loaded, right now this is not the case, because of things like: https://github.com/zeachco/stubborn-server/blob/master/server/config.js#L5

### PR DESCRIPTION
**Pull request by ruyadorno**
Fixes #5

### CODE REVIEW

**Comment by ruyadorno** [comment]
ping @zeachco fixed linting error

**Comment by ruyadorno** [comment]
euh... do not merge yet, just realize there are other places where the config file is required 😕 sorry

File: server/config.js [hunk 1]
```diff
@@ -2,7 +2,13 @@
 
 const path = require('path');
 const log = require('./logger');
-let config = require(path.join(process.cwd(), 'stubborn'));
+let config;
+
+try {
+  config = require(path.join(process.cwd(), 'stubborn'));
+} catch (e) {
+  config = {};
```
Comment (zeachco) [inline server/config.js]: `log.error(\`cannot find "stubborn.js" or "stubborn.json" in ${process.cwd()}\`)` might be a good warning to put here

**Comment by zeachco** [comment]
So the strategy would be to pass down the config object instead of getting it from the local module `config` right?

**Comment by ruyadorno** [comment]
👍 yep, awesome idea, I'll just send the config module as a param instead

File: index.js [hunk 2]
```diff
@@ -4,7 +4,7 @@ const fileConfig = require('./server/config');
 
 const api = {};
 api.log = require('./server/logger');
-api.start = (config) => fileConfig(config) && require('./server') && api;
+api.start = (config) => fileConfig(config) && require('./server')(config) && api;
```
Comment (ruyadorno) [inline index.js]: send the `config` obj down to the server as a param

File: server/config.js (hunk 1 above)
Comment (ruyadorno) [inline server/config.js]: meh, but if it's optional... 

maybe we postpone the requiring so that we can test if the `options` 👇 exists, if there's no `options` and no `stubborn.js` file then we might `log.error` that

File: server/fallback.js [hunk 3]
```diff
@@ -2,24 +2,27 @@
...
-          req.headers['X-Server-Proxy'] = 'Stubborn-server';
-          return req;
-        }
-      })(req, res, next);
-    });
-  } else { // We assume the target is a local folder if not an url
-    app.use(key.replace(/\*$/, ''), express.static(target));
-  }
-});
+module.exports = config => {
```
Comment (ruyadorno) [inline server/fallback.js]: `config` is the `server/config.js` module received as a parameter now

File: server/index.js [hunk 4]
```diff
@@ -2,14 +2,18 @@
 
 const app = require('./app');
 const log = require('./logger');
-const conf = require('./config')();
 
-require('./mocks');
-require('./fallback');
-require('./dead-end');
+module.exports = options => {
+  const config = require('./config')(options);
```
Comment (ruyadorno) [inline server/index.js]: initializes the config module just once and send it as a parameter to the other modules that needs it 👇

File: server/mocks.js [hunk 5]
```diff
@@ -2,59 +2,61 @@
...
 const memoryDb = require('./memory-db');
-const config = require('./config')();
 const app = require('./app');
 
-const utils = {
-  config: config,
-  log: log.mock,
-  db: memoryDb
-};
+module.exports = config => {
```
Comment (ruyadorno) [inline server/mocks.js]: same, no requiring of `./config` it's now a parameter

**Comment by ruyadorno** [comment]
dependency injection FTW

**Comment by ruyadorno** [comment]
✅ ready to go

**Comment by zeachco** [comment]
:package: :rocket: !

**Comment by zeachco** [comment]
:clap:
